name = "001-time"
account_id = "bcf9a6a801dff102ae806a8039defd01"
main = "./index.mjs"
compatibility_date = "2022-09-08"

[durable_objects]
bindings = [{name = "DAT_TIME", class_name = "DatTime"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DatTime"]